# -*- coding: utf-8 -*-
"""Forest_fire.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b7EN69I1rmseMH0md1t6FefpcOi02d4u
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv("/content/Algerian_forest_fires_dataset.csv")
df.head()

df = pd.read_csv("Algerian_forest_fires_dataset.csv")

# Remove leading/trailing spaces from column names
df.columns = df.columns.str.strip()

# Identify non-'Classes' columns
non_class_cols = [col for col in df.columns if col.lower() != "classes"]

# Clean and convert all non-class columns to float
for col in non_class_cols:
    df[col] = pd.to_numeric(df[col].astype(str).str.replace(r'[^\d.-]', '', regex=True), errors='coerce')

# Keep 'Classes' as-is and drop rows with NaNs in numeric columns
df = df.dropna(subset=non_class_cols)

# Save to new CSV
df.to_csv("Algerian_forest_fires_cleaned.csv", index=False)

df.info()

df.describe()

df.drop(columns = ["day", "month", "year"], inplace = True)
df.head()

df.isnull().sum()

df.dropna(inplace=True)

df.columns

from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
df['Classes'] = label_encoder.fit_transform(df['Classes'])
df.head()

from sklearn.model_selection import train_test_split
x = df.drop(columns=["Classes"])  # Features
x

y = df["Classes"]
y

# Step 4: Split data into training and testing sets (80% train, 20% test)
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.2, random_state=42)

# Step 6: Train the Logistic Regression model
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(xtrain, ytrain)

# Step 7: Make predictions
ypred = model.predict(xtest)

# Step 8: Evaluate the model
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
accuracy = accuracy_score(ytest, ypred)
class_report = classification_report(ytest, ypred)

# Print results
print("Model Accuracy:", accuracy)
print("Classification Report:\n", class_report)

import joblib
joblib.dump(model, "forest_fire_model.pkl")

from google.colab import files
files.download("forest_fire_model.pkl")